---
- name: Install Samba packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - samba-common
      - samba
      - samba-client
      - samba-vfs-modules

- name: Increase the allowed maximum number of open files (a Windows limitation)
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    state: present
    regexp: '^\* - nofile [0-9]+'
    insertbefore: '^# End of file'
    line: '* - nofile 16384'
  notify:
    - Restart Samba services

- name: Check that Samba isn't set up as both a WINS server and client
  ansible.builtin.fail:
    msg: "Samba can be either a WINS Server, or a WINS Client, but NOT both"
  when: (samba_wins_support is defined and samba_wins_support != false) and samba_wins_server is defined

- name: Warn about insecure guest access
  ansible.builtin.fail:
    msg: "It is not possible to enable encryption on shares with guest access enabled; automatically defaulting to 'off' in those cases"
  when: samba_force_encryption and samba_usershare_allow_guests
  ignore_errors: True

- name: Push out Samba configuration file
  ansible.builtin.template:
    dest: "{{ samba_config_file }}"
    src: smb.conf.j2
    validate: 'testparm -s %s'
    owner: root
    group: root
    mode: "0644"
  register: samba_testparm
  notify:
    - Restart Samba services

- name: Create 'username map' file if needed
  ansible.builtin.template:
    dest: "{{ samba_username_map_file }}"
    src: smbusers.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart Samba services
  when: samba_username_map is defined

- name: Configure any 'dfree command'
  ansible.builtin.include_tasks: dfree_command.yml

- name: Make sure Samba loads any changes made to its configuration before continuing
  ansible.builtin.meta: flush_handlers

- name: Create Samba users if they don't exist, else make sure they have the correct password set
  no_log: "{{ global_hide_sensitive_output | default(true) }}"
  ansible.builtin.shell: >
    set -o nounset -o pipefail -o errexit &&
    if (pdbedit --user={{ item.name }} 2>&1 > /dev/null); then \
      if ! (smbclient -U {{ item.name }}%{{ item.password }} -L 127.0.0.1 2>&1 > /dev/null); then \
        (echo '{{ item.password }}'; echo '{{ item.password }}') | smbpasswd {{ item.name }}; \
      fi; \
    else \
      (echo {{ item.password }}; echo {{ item.password }}) | smbpasswd -s -a {{ item.name }}; \
    fi
  args:
    executable: /bin/bash
  with_items: "{{ samba_users }}"
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout or 'New SMB password' in create_user_output.stdout"
